module.exports = {
	title: 'VueFlux',
	description: 'Documentation and demos of vue slider VueFlux',
	base: '/vue-flux-docs/',
	dest: 'docs/',
	themeConfig: {
		search: false,
		nav: [
			{ text: 'Home', link: '/' },
			{ text: 'Documentation',
				items: [
					{ text: 'v5', link: '/v5/' },
					{ text: 'v6', link: '/v6/' },
				],
			},
			{ text: 'Demos', link: '/demos/' },
			{ text: 'Github', link: 'https://github.com/ragnarlotus/vue-flux' },
		],
		sidebar: {
			'/v5/': [
				['/v5/', 'Overview'],
				['/v5/changelog', 'Changelog'],
				['/v5/installation-and-usage', 'Installation and usage'],
				['/v5/templating', 'Templating'],
				['/v5/ssr-with-nuxt', 'SSR with Nuxt'],
				{
					title: 'Components',
					path: '/v5/components/vue-flux',
					children: [
						['/v5/components/vue-flux', 'VueFlux'],
						['/v5/components/flux-parallax', 'FluxParallax'],
						['/v5/components/flux-caption', 'FluxCaption'],
						['/v5/components/flux-controls', 'FluxControls'],
						['/v5/components/flux-index', 'FluxIndex'],
						['/v5/components/flux-pagination', 'FluxPagination'],
						['/v5/components/flux-image', 'FluxImage'],
						['/v5/components/flux-wrapper', 'FluxWrapper'],
						['/v5/components/flux-cube', 'FluxCube'],
						['/v5/components/flux-grid', 'FluxGrid'],
						['/v5/components/flux-vortex', 'FluxVortex'],
						['/v5/components/flux-thumb', 'FluxThumb'],
					]
				},
				{
					title: 'Transitions',
					path: '/v5/transitions/',
					children: [
						['/v5/transitions/blinds2d', 'Blinds 2D'],
						['/v5/transitions/blinds3d', 'Blinds 3D'],
						['/v5/transitions/blocks1', 'Blocks 1'],
						['/v5/transitions/blocks2', 'Blocks 2'],
						['/v5/transitions/book', 'Book'],
						['/v5/transitions/camera', 'Camera'],
						['/v5/transitions/concentric', 'Concentric'],
						['/v5/transitions/cube', 'Cube'],
						['/v5/transitions/explode', 'Explode'],
						['/v5/transitions/fade', 'Fade'],
						['/v5/transitions/fall', 'Fall'],
						['/v5/transitions/kenburn', 'Kenburn'],
						['/v5/transitions/round1', 'Round 1'],
						['/v5/transitions/round2', 'Round 2'],
						['/v5/transitions/slide', 'Slide'],
						['/v5/transitions/swipe', 'Swipe'],
						['/v5/transitions/warp', 'Warp'],
						['/v5/transitions/waterfall', 'Waterfall'],
						['/v5/transitions/wave', 'Wave'],
						['/v5/transitions/zip', 'Zip'],
					],
				},
				['/v5/custom-transitions', 'Custom transitions'],
			],

			'/v6/': [
				['/v6/', 'Overview'],
				['/v6/changelog', 'Changelog'],
				['/v6/installation-and-usage', 'Installation and usage'],
				['/v6/ssr-with-nuxt', 'SSR with Nuxt'],
				{
					title: 'Components',
					path: '/v6/components/',
					children: [
						['/v6/components/vue-flux', 'VueFlux'],
						['/v6/components/flux-button', 'FluxButton'],
						['/v6/components/flux-cube', 'FluxCube'],
						['/v6/components/flux-grid', 'FluxGrid'],
						['/v6/components/flux-image', 'FluxImage'],
						['/v6/components/flux-parallax', 'FluxParallax'],
						['/v6/components/flux-transition', 'FluxTransition'],
						['/v6/components/flux-vortex', 'FluxVortex'],
						['/v6/components/flux-wrapper', 'FluxWrapper'],
					],
				}, {
					title: 'Complements',
					path: '/v6/complements/',
					children: [
						['/v6/complements/flux-caption', 'FluxCaption'],
						['/v6/complements/flux-controls', 'FluxControls'],
						['/v6/complements/flux-index', 'FluxIndex'],
						['/v6/complements/flux-pagination', 'FluxPagination'],
						['/v6/complements/flux-preloader', 'FluxPreloader'],
					],
				}, {
					title: 'Transitions',
					path: '/v6/transitions/',
					children: [
						['/v6/transitions/blinds2d', 'Blinds 2D'],
						['/v6/transitions/blinds3d', 'Blinds 3D'],
						['/v6/transitions/blocks1', 'Blocks 1'],
						['/v6/transitions/blocks2', 'Blocks 2'],
						['/v6/transitions/book', 'Book'],
						['/v6/transitions/camera', 'Camera'],
						['/v6/transitions/concentric', 'Concentric'],
						['/v6/transitions/cube', 'Cube'],
						['/v6/transitions/explode', 'Explode'],
						['/v6/transitions/fade', 'Fade'],
						['/v6/transitions/fall', 'Fall'],
						['/v6/transitions/kenburn', 'Kenburn'],
						['/v6/transitions/round1', 'Round 1'],
						['/v6/transitions/round2', 'Round 2'],
						['/v6/transitions/slide', 'Slide'],
						['/v6/transitions/swipe', 'Swipe'],
						['/v6/transitions/warp', 'Warp'],
						['/v6/transitions/waterfall', 'Waterfall'],
						['/v6/transitions/wave', 'Wave'],
						['/v6/transitions/zip', 'Zip'],
					],
				},
				['/v6/custom-transitions', 'Custom transitions'],
			],
			'/demos/': [
				['/demos/', 'Demos'],
				{
					title: 'VueFlux',
					path: '/demos/vue-flux/',
					children: [
						['/demos/vue-flux/flux-caption', 'FluxCaption'],
						['/demos/vue-flux/flux-controls', 'FluxControls'],
						['/demos/vue-flux/flux-index', 'FluxIndex'],
						['/demos/vue-flux/flux-pagination', 'FluxPagination'],
						['/demos/vue-flux/flux-preloader', 'FluxPreloader'],
					],
				},
				['/demos/flux-image', 'FluxImage'],
				['/demos/flux-button', 'FluxButton'],
				['/demos/flux-cube', 'FluxCube'],
				['/demos/flux-grid', 'FluxGrid'],
				['/demos/flux-vortex', 'FluxVortex'],
				['/demos/flux-transition', 'FluxTransition'],
				['/demos/flux-parallax', 'FluxParallax'],
				{
					title: 'Transitions',
					path: '/demos/transitions/',
					children: [
						['/demos/transitions/blinds2d', 'Blinds 2D'],
						['/demos/transitions/blinds3d', 'Blinds 3D'],
						['/demos/transitions/blocks1', 'Blocks 1'],
						['/demos/transitions/blocks2', 'Blocks 2'],
						['/demos/transitions/book', 'Book'],
						['/demos/transitions/camera', 'Camera'],
						['/demos/transitions/concentric', 'Concentric'],
						['/demos/transitions/cube', 'Cube'],
						['/demos/transitions/explode', 'Explode'],
						['/demos/transitions/fade', 'Fade'],
						['/demos/transitions/fall', 'Fall'],
						['/demos/transitions/kenburn', 'Kenburn'],
						['/demos/transitions/round1', 'Round 1'],
						['/demos/transitions/round2', 'Round 2'],
						['/demos/transitions/slide', 'Slide'],
						['/demos/transitions/swipe', 'Swipe'],
						['/demos/transitions/warp', 'Warp'],
						['/demos/transitions/waterfall', 'Waterfall'],
						['/demos/transitions/wave', 'Wave'],
						['/demos/transitions/zip', 'Zip'],
					],
				},
			],
		},
	},
	plugins: [
		[
			'@vuepress/google-analytics',
			{
				'ga': 'UA-1241862-15' // UA-00000000-0
			}
		]
	]
}
